# Generated by Django 5.0.14 on 2025-07-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=100)),
                ('contenuto', models.CharField(max_length=255)),
                ('stato', models.BooleanField(default=False)),
                ('scadenza', models.DateField()),
            ],
        ),
    ]
