# Generated by Django 5.0.14 on 2025-07-23 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_shared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('data_caricamento', models.DateField(auto_created=True, auto_now_add=True)),
                ('id_documento', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=30)),
                ('documento', models.FileField(upload_to='documents/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to=settings.AUTH_USER_MODEL)),
                ('shared_document', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
